### ISSUE TITLE
Documentación

### ISSUE THREAD

**Issue by Gabriela1832** [vazqujaa/DAJAYA#1]
[inte2.docx](https://github.com/vazqujaa/DAJAYA/files/1750359/inte2.docx)

**Comment by Rocha097** [comment]
WBS
[Estructura de desarrollo del trabajo.docx](https://github.com/vazqujaa/DAJAYA/files/1750377/Estructura.de.desarrollo.del.trabajo.docx)

**Comment by emacp** [comment]
[diagrama de gant.xlsx](https://github.com/vazqujaa/DAJAYA/files/1750382/diagrama.de.gant.xlsx)

**Comment by Rocha097** [comment]
- DIAGRAMA WBS
[Estructura de desarrollo del trabajo.docx](https://github.com/vazqujaa/DAJAYA/files/1750381/Estructura.de.desarrollo.del.trabajo.docx)#

**Comment by emacp** [comment]
[DAJAYA boseto.pptx](https://github.com/vazqujaa/DAJAYA/files/1750383/DAJAYA.boseto.pptx)

**Comment by emacp** [comment]
[Roles.docx](https://github.com/vazqujaa/DAJAYA/files/1750384/Roles.docx)
